[package]
name = "hieroglyphic"
version = "1.0.0"
authors = ["FineFindus <FineFindus@proton.me>"]
edition = "2021"
description = """Search through over 1000 different LaTeX symbols by sketching"""
license = "GPL-3.0"
repository = "https://github.com/FineFindus/tex-match/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
# GTK
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.8", package = "gtk4", features = ["v4_12"] }
adw = { package = "libadwaita", version = "0.6", features = ["v1_4"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
gdk-pixbuf = "0.19"
pango = "0.19"
cairo-rs = "0.19"
# TeX classification
detexify = "0.4.0"
itertools = "0.12.1"
async-channel = "2.2.0"
