name: tex-match
icon: snap/gui/tex-match.svg
adopt-info: tex-match

base: core18
confinement: strict

build-packages:
  - gcc
  - libc6-dev

parts:
  tex-match:
    plugin: rust
    source: ../
    parse-info:
      - data/fyi.zoey.TeX-Match.metainfo.xml
    override-build: |
      cd TeX-Match-Linux
      snapcraftctl build

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: fyi.zoey.TeX-Match

apps:
  tex-match:
    command: bin/tex-match
    extensions: [gnome-3-34]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
    slots:
      - dbus-daemon
    common-id: fyi.zoey.TeX-Match
